CREATE DATABASE IF NOT EXISTS QuanLyHocTap;
USE QuanLyHocTap;

CREATE TABLE SinhVien (
    MaSV VARCHAR(20) PRIMARY KEY,
    HoTen NVARCHAR(100)
);

CREATE TABLE MonHoc (
    MaMonHoc VARCHAR(20) PRIMARY KEY,
    TenMon NVARCHAR(100),
    SoTinChi INT,
    MaSV VARCHAR(20)
);

CREATE TABLE MucTieu (
    MaMucTieu VARCHAR(20) PRIMARY KEY, 
    NoiDung NVARCHAR(255),
    MaMonHoc VARCHAR(20)
);
